pluginGroup=de.halirutan.keypromoterx
pluginName=Key Promoter X
pluginRepositoryUrl=https://github.com/halirutan/IntelliJ-Key-Promoter-X
pluginVersion=2026.1
pluginSinceBuild=241
pluginUntilBuild=
# Plugin Verifier integration -> https://github.com/JetBrains/gradle-intellij-plugin#plugin-verifier-dsl
# See https://jb.gg/intellij-platform-builds-list for available build versions
platformVersion=2026.1
gradleVersion=9.4.1
kotlin.stdlib.default.dependency=false
org.gradle.configuration-cache=false
org.gradle.caching=false
# suppress inspection "WrongPropertyKeyValueDelimiter"
# suppress inspection "UnusedProperty"
--add-exports java.base/jdk.internal.vm=ALL-UNNAMED